### ISSUE TITLE
The linked Google Doc is private

### ISSUE THREAD

**Issue by Claytonious** [Unity-Technologies/UIElementsExamples#13]
This repo's README says to refer to the docs at https://docs.google.com/a/unity3d.com/document/d/186aHiyAuYezcXtu3y_xpygjxDf5OAD79VOlH7sEDxNg/edit?usp=sharing, but that google doc is not publicly accessible.

**Comment by mathieum-unity** [comment]
Hi Clay, version 2017.3 of the documentation is still WIP. In the meantime, you can read the 2017.2 version here:
https://docs.google.com/document/d/1ZmtPhJqridaJuzoMJUtBlDq26uHHopdF8M1v6H9McTo/edit#heading=h.9kkpbg5kzeeq
